# Generated by Django 5.0.6 on 2024-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
