# Generated by Django 5.0.6 on 2024-07-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='products/images/'),
        ),
    ]
